server:
  port: 8083

spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: mugastiabrian@gmail.com
    password: 258036bm,
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
